SHOW DATABASES;
USE customer_behavior;

SELECT *
FROM customer_shopping
LIMIT 20;

##Q1. What is the total revenue generated by male vs. female customers? (Bootcamp Analysis)

SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer_shopping
GROUP BY gender;

/*Male customers generated the highest total revenue, contributing 157,890 compared to 75,191 from female customers. 
This indicates a substantial difference in revenue contribution between genders and may warrant further investigation into customer preferences and purchasing behavior.
  
##Q2. Discount Customers Above Average Spending (Bootcamp Analysis)
#Business Question : Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer_shopping
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer_shopping
);

/*A total of 839 customers used discounts while still spending above the overall average purchase amount. 
This suggests that discounts were effective in encouraging higher-value purchases rather than simply attracting low-spending customers.
The results indicate that promotional strategies may have positively influenced customer spending behavior.


##Q3.Product Rating Analysis (Bootcamp Analysis) 
#Business Question : Which are the top 5 products with the highest average review rating?

SELECT
    item_purchased,
    ROUND(AVG(review_rating),2) AS average_product_rating
FROM customer_shopping
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

/*Gloves received the highest average review rating (3.86), followed closely by Sandals (3.84) and Boots (3.82).
 The small differences among the top-rated products suggest relatively consistent customer satisfaction across these items. 
 Businesses may consider highlighting these products in marketing campaigns, 
as they demonstrate stronger customer approval compared to other products in the dataset.

#Q4.Shipping Type Purchase Analysis (Bootcamp Analysis)
#Business Question : Compare the average Purchase Amounts between Standard and Express Shipping. 
 
SELECT shipping_type,
    ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer_shopping
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

/*Customers who selected Express Shipping recorded a slightly higher average purchase amount (60.48) compared to those using Standard Shipping (58.46).
 Although the difference is relatively small, it may indicate that customers making higher-value purchases are somewhat more willing to pay for faster delivery services.
 
##Q5. Subscription Revenue Analysis (Bootcamp Analysis)
#Business Question : Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shopping
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

/*Non-subscribed customers generated the majority of revenue (170,436) and recorded a slightly higher average purchase amount (59.87) 
compared to subscribed customers (59.49). Additionally, non-subscribers represented a much larger customer base. 
These findings suggest that subscription status alone was not associated with higher spending behavior in this dataset.

##Q6. Product Discount Utilization Analysis (Bootcamp Analysis)
#Business Question : Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
    item_purchased,
    ROUND(
        100 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

/*insight : Hat recorded the highest discount utilization rate at 50.00%, 
followed closely by Sneakers (49.66%) and Coat (49.07%). 
The relatively small differences among the top five products suggest that discount usage was fairly consistent across these items. 
This indicates that promotional discounts played a similar role in influencing purchases across multiple product categories 
rather than being concentrated on a single product

##Q7. Customer Segmentation Analysis (Bootcamp Analysis)
#Business Question : Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

WITH customer_type AS (
    SELECT customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

/*Insight : Loyal customers accounted for the vast majority of the customer base, 
representing 3,116 customers compared to 701 Returning customers and only 83 New customers. 
This suggests that the business has a strong foundation of repeat purchasers and customer retention. However,
the relatively small number of New customers may indicate an opportunity to strengthen customer acquisition efforts and attract new buyers.

##Q8.Top Products by Category Analysis (Bootcamp Analysis)
#Business Question : What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping
    GROUP BY category, item_purchased
)

SELECT
    item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

/*Insight : Several products consistently stood out as the most frequently purchased items within their categories. 
Jewelry led the Accessories category with 171 orders, while Blouse and Pants jointly ranked first in Clothing with 171 orders each. In Footwear, 
Sandals recorded the highest demand with 160 orders, and Jacket was the top-performing product in Outerwear with 163 orders.
The relatively small differences in order volume among the top-ranked products 
suggest that customer demand was fairly balanced within each category rather than being dominated by a single product.

##Q9. Repeat Buyers and Subscription Analysis (Bootcamp Analysis) 
#Business Question : Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

/*Insight : Among customers with more than five previous purchases, the majority were non-subscribers (2,518 customers), 
compared to 958 subscribed customers. This suggests that repeat purchasing behavior was not strongly associated with subscription status in this dataset. 
Many customers continued to make frequent purchases without enrolling in a subscription program, 
indicating that factors other than subscriptions may play a larger role in driving customer loyalty.

##Q10. Revenue Contribution by Age Group (Bootcamp Analysis) 
#Business Question : What is the revenue contribution of each age group? 

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping
GROUP BY age_group
ORDER BY total_revenue DESC;

/*Insight : Young Adult customers generated the highest total revenue, contributing 62,143 in sales. However, 
the revenue distribution across all age groups was relatively balanced, with each segment contributing between 55,000 and 62,000 in total revenue. 
This suggests that the business serves a diverse customer base and is not heavily dependent on a single age group for revenue generation.


SELECT * FROM customer_shopping LIMIT 10;